=== FusRoman/Fink_MM/fink_grb/observatory/observatory_schema_version_1.0.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "fink_grb/instruments/instrument_schema_version_1.0.json",
    "title": "Instrument",
    "description": "The description of an astronomical instrument sending alerts on the General Coordinates network",
    "type": "object",
    "properties": {
      "name": {
        "description": "name of the instrument",
        "type": "string"
      },
      "//gcn_description": {
        "description": "URL where to find the GCN description for this instrument",
        "type": "string"
      },
      "packet_type": {
        "description": "packet type to listen by the GCN stream service",
        "type": "array",
        "items": {
            "type": "integer"
        },
        "minItems": 1,
        "uniqueItems": true
      },
      "kafka_topics": {
        "description": "the kafka topics to listen for this instrument",
        "type": "array",
        "items": {
            "type": "string"
        },
        "minItems": 1,
        "uniqueItems": true
      }
    },
    "required": [ "name", "packet_type", "kafka_topics"]
  }

=== FusRoman/Fink_MM/fink_grb/observatory/IceCube/icecube.json
{
    "name": "ICECUBE",
    "//gcn_description": "https://gcn.gsfc.nasa.gov/amon.html",
    "packet_type": [
        157, 173, 174, 176
    ],
    "kafka_topics": [
        "gcn.classic.voevent.ICECUBE_ASTROTRACK_BRONZE",
        "gcn.classic.voevent.ICECUBE_ASTROTRACK_GOLD",
        "gcn.classic.voevent.ICECUBE_CASCADE"
    ]
}

=== FusRoman/Fink_MM/fink_grb/observatory/Integral/integral.json
{
    "name": "INTEGRAL",
    "//gcn_description": "https://gcn.gsfc.nasa.gov/integral.html",
    "packet_type": [
        53, 54, 56
    ],
    "kafka_topics": [
        "gcn.classic.voevent.INTEGRAL_OFFLINE",
        "gcn.classic.voevent.INTEGRAL_POINTDIR",
        "gcn.classic.voevent.INTEGRAL_REFINED",
        "gcn.classic.voevent.INTEGRAL_SPIACS",
        "gcn.classic.voevent.INTEGRAL_WAKEUP",
        "gcn.classic.voevent.INTEGRAL_WEAK"
    ]
}
