=== FusRoman/Fink_MM/fink_grb/observatory/observatory_schema_version_1.1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "fink_grb/instruments/instrument_schema_version_1.0.json",
  "title": "Instrument",
  "description": "The description of an astronomical observatory sending alerts on the General Coordinates network",
  "type": "object",
  "properties": {
    "name": {
      "description": "name of the instrument",
      "type": "string"
    },
    "//gcn_description": {
      "description": "URL where to find the GCN description for this instrument",
      "type": "string"
    },
    "gcn_file_format": {
      "description": "gcn file format get from the gcn kafka stream",
      "type": "string"
    },
    "packet_type": {
      "description": "packet type to listen by the GCN stream service",
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "kafka_topics": {
      "description": "the kafka topics to listen for this instrument",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "grb_detection_rate": {
      "description": "number of gamma ray burst detection per year for the given observatory (if a gamma ray bust observatory)",
      "type": "integer"
    }
  },
  "required": [
    "name",
    "packet_type",
    "kafka_topics"
  ]
}

=== FusRoman/Fink_MM/fink_mm/observatory/Swift/swift.json
{
    "name": "SWIFT",
    "//gcn_description": "https://gcn.gsfc.nasa.gov/swift.html",
    "gcn_file_format": "xml",
    "packet_type": [
        61,
        63,
        65,
        67,
        81,
        84,
        97
    ],
    "kafka_topics": [
        "gcn.classic.voevent.SWIFT_ACTUAL_POINTDIR",
        "gcn.classic.voevent.SWIFT_BAT_ALARM_LONG",
        "gcn.classic.voevent.SWIFT_BAT_ALARM_SHORT",
        "gcn.classic.voevent.SWIFT_BAT_GRB_ALERT",
        "gcn.classic.voevent.SWIFT_BAT_GRB_LC",
        "gcn.classic.voevent.SWIFT_BAT_GRB_LC_PROC",
        "gcn.classic.voevent.SWIFT_BAT_GRB_POS_ACK",
        "gcn.classic.voevent.SWIFT_BAT_GRB_POS_NACK",
        "gcn.classic.voevent.SWIFT_BAT_GRB_POS_TEST",
        "gcn.classic.voevent.SWIFT_BAT_KNOWN_SRC",
        "gcn.classic.voevent.SWIFT_BAT_MONITOR",
        "gcn.classic.voevent.SWIFT_BAT_QL_POS",
        "gcn.classic.voevent.SWIFT_BAT_SCALEDMAP",
        "gcn.classic.voevent.SWIFT_BAT_SLEW_POS",
        "gcn.classic.voevent.SWIFT_BAT_SUB_THRESHOLD",
        "gcn.classic.voevent.SWIFT_BAT_SUBSUB",
        "gcn.classic.voevent.SWIFT_BAT_TRANS",
        "gcn.classic.voevent.SWIFT_FOM_OBS",
        "gcn.classic.voevent.SWIFT_FOM_PPT_ARG_ERR",
        "gcn.classic.voevent.SWIFT_FOM_SAFE_POINT",
        "gcn.classic.voevent.SWIFT_FOM_SLEW_ABORT",
        "gcn.classic.voevent.SWIFT_POINTDIR",
        "gcn.classic.voevent.SWIFT_SC_SLEW",
        "gcn.classic.voevent.SWIFT_TOO_FOM",
        "gcn.classic.voevent.SWIFT_TOO_SC_SLEW",
        "gcn.classic.voevent.SWIFT_UVOT_DBURST",
        "gcn.classic.voevent.SWIFT_UVOT_DBURST_PROC",
        "gcn.classic.voevent.SWIFT_UVOT_EMERGENCY",
        "gcn.classic.voevent.SWIFT_UVOT_FCHART",
        "gcn.classic.voevent.SWIFT_UVOT_FCHART_PROC",
        "gcn.classic.voevent.SWIFT_UVOT_POS",
        "gcn.classic.voevent.SWIFT_UVOT_POS_NACK",
        "gcn.classic.voevent.SWIFT_XRT_CENTROID",
        "gcn.classic.voevent.SWIFT_XRT_EMERGENCY",
        "gcn.classic.voevent.SWIFT_XRT_IMAGE",
        "gcn.classic.voevent.SWIFT_XRT_IMAGE_PROC",
        "gcn.classic.voevent.SWIFT_XRT_LC",
        "gcn.classic.voevent.SWIFT_XRT_POSITION",
        "gcn.classic.voevent.SWIFT_XRT_SPECTRUM",
        "gcn.classic.voevent.SWIFT_XRT_SPECTRUM_PROC",
        "gcn.classic.voevent.SWIFT_XRT_SPER",
        "gcn.classic.voevent.SWIFT_XRT_SPER_PROC",
        "gcn.classic.voevent.SWIFT_XRT_THRESHPIX",
        "gcn.classic.voevent.SWIFT_XRT_THRESHPIX_PROC"
    ],
    "grb_detection_rate": 100
}

=== FusRoman/Fink_MM/fink_mm/observatory/Integral/integral.json
{
    "name": "INTEGRAL",
    "//gcn_description": "https://gcn.gsfc.nasa.gov/integral.html",
    "gcn_file_format": "xml",
    "packet_type": [
        53,
        54,
        56
    ],
    "kafka_topics": [
        "gcn.classic.voevent.INTEGRAL_OFFLINE",
        "gcn.classic.voevent.INTEGRAL_POINTDIR",
        "gcn.classic.voevent.INTEGRAL_REFINED",
        "gcn.classic.voevent.INTEGRAL_SPIACS",
        "gcn.classic.voevent.INTEGRAL_WAKEUP",
        "gcn.classic.voevent.INTEGRAL_WEAK"
    ],
    "grb_detection_rate": 60
}

=== FusRoman/Fink_MM/fink_grb/observatory/Fermi/fermi.json
{
    "name": "Fermi",
    "//gcn_description": "https://gcn.gsfc.nasa.gov/fermi.html",
    "packet_type": [
        111, 112, 115,
        120, 121, 127,
        123, 125
    ],
    "kafka_topics": [
        "gcn.classic.voevent.FERMI_GBM_ALERT",
        "gcn.classic.voevent.FERMI_GBM_FIN_POS",
        "gcn.classic.voevent.FERMI_GBM_FLT_POS",
        "gcn.classic.voevent.FERMI_GBM_GND_POS",
        "gcn.classic.voevent.FERMI_GBM_LC",
        "gcn.classic.voevent.FERMI_GBM_POS_TEST",
        "gcn.classic.voevent.FERMI_GBM_SUBTHRESH",
        "gcn.classic.voevent.FERMI_GBM_TRANS",
        "gcn.classic.voevent.FERMI_LAT_GND",
        "gcn.classic.voevent.FERMI_LAT_MONITOR",
        "gcn.classic.voevent.FERMI_LAT_OFFLINE",
        "gcn.classic.voevent.FERMI_LAT_POS_DIAG",
        "gcn.classic.voevent.FERMI_LAT_POS_INI",
        "gcn.classic.voevent.FERMI_LAT_POS_TEST",
        "gcn.classic.voevent.FERMI_LAT_POS_UPD",
        "gcn.classic.voevent.FERMI_LAT_TRANS",
        "gcn.classic.voevent.FERMI_POINTDIR",
        "gcn.classic.voevent.FERMI_SC_SLEW"
    ],
    "grb_detection_rate": 250
}
